import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next blog demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Blog demo
        </h1>

        <p className={styles.description}>
          Static Site Generator
        </p>
        <div className={styles.grid}>
          {
            posts.map((post) => (

              <div key={post.id} href="https://nextjs.org/docs" className={styles.card}>
                <h2>{post.title}</h2>
                <p>{post.description}</p>
              </div>

            ))
          }
        </div>

      </main>

      <footer className={styles.footer}>
        <span>Posts count: </span>
      </footer>
    </div>
  )
}

export async function getStaticProps() {

  const req = await fetch('https://63965ff1a68e43e418027940.mockapi.io/post');
  const data = await req.json();


  return {
    props: { posts: data },
  }
}

